name: CleanPing
version: '${project.version}'
main: it.frafol.cleanping.bukkit.CleanPing
authors: [ frafol ]
folia-supported: true
api-version: 1.13
description: "Adds /ping command to check your and player's ping."
softdepend:
  - PlaceholderAPI
commands:
  cleanping:
    description: Show your ping
    aliases: [ ping ]
  pingreload:
    description: Reload the plugin
    aliases: [ cleanpingreload ]